# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mulltometro' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mulltometro
	pod 'Firebase/Core'
	pod 'Firebase/Database'
	pod 'Firebase/Auth'
	pod 'Firebase/Storage'
	pod 'R.swift'
  target 'MulltometroTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MulltometroUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
