# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mulltometro' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mulltometro
	pod 'R.swift', '5.0.0.alpha.2'
	pod 'Kingfisher', '~> 4.0'
	pod 'IQKeyboardManager'
  target 'MulltometroTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MulltometroUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
