# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "This lane generate .ipa file to app upload"

  lane :generateIPA do
    # add actions here: https://docs.fastlane.tools/actions

    build_ios_app(
      configuration: "Debug",
      scheme: "Mulltometro",
     	clean: true,
     	export_method: 'development',
      output_directory: "~/Desktop", # Destination directory. Defaults to current directory.
      output_name: "mulltometroBuild.ipa",
    )
  end
  
  lane :slackMessage do
       slack(
           message: "Master updated with a new version",
           success: true,
           slack_url: "https://hooks.slack.com/services/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"
       )
   end

  lane :uploadToTestFlight do
    commit = last_git_commit

    slack(
           message: commit[:message],
           success: true,
           slack_url: "https://hooks.slack.com/services/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"
       )
  end
  
end
