# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "This lane generate .ipa file to app upload"

  lane :generateIPA do
    # add actions here: https://docs.fastlane.tools/actions

    build_ios_app(
      configuration: "Release",
      scheme: "Mulltometro",
     	clean: true,
     	export_method: 'app-store',
      output_directory: "~/Desktop", # Destination directory. Defaults to current directory.
      output_name: "mulltometroBuild.ipa",
    )
  end

  lane :uploadToTestFlight do
    commit = last_git_commit
    
    upload_to_testflight(
      ipa: "~/Desktop/mulltometroBuild.ipa",
      username: "georgegomees@gmail.com",
      team_id: "118596484",
      app_identifier: "com.crowcode.Multometro",
      changelog: "Change textfield color text to white and missing rounded corner in buttons",
      beta_app_description: "Change textfield color text to white and missing rounded corner in buttons"
    )
  end
  
  lane :beta do 
    increment_build_number

    gym(
      export_method: "app-store"
    )

    pilot(skip_wainting_for_build_processing: true)
  end

  lane :codeSign do
    cert(
      username: "georgegomees@gmail.com",
      team_id: "J8JPD2534R"
    )
    sigh(
      force: true,
      username: "georgegomees@gmail.com",
      app_identifier: "com.crowcode.Multometro",
      team_id: "J8JPD2534R"
    )
  end

  lane :slackMessage do
    commit = last_git_commit
    slack(
      message: commit[:message],
      success: true,
      slack_url: "https://hooks.slack.com/services/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"
    )
  end
end

